### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BeastyBlacksmith** [julia-users-berlin/julia-users-workshop#1]
Which license should we put this under? I was thinking of CC0, thats a one-way-street though, so everybody should be fine with it.

CC: @pfitzseb @frankhuettner @daveh19

**Comment by daveh19** [comment]
I'm pretty open. Glad you ask it now, rather than later of course. If you think you might want to use it for something specific later, then I'd advise MIT licence. Otherwise any of the GNU or CC licences work for me. It's both code and text, so GNU/MIT might be more appropriate...

**Comment by daveh19** [comment]
Maybe, for process, it would be worth getting anybody who contributed already (to the first workshop) to agree here to the new licence. I guess that's what you're going for with the name tags above.

**Comment by pfitzseb** [comment]
By default I'd vote for MIT, but considering there's probably not going to be much reuseable code in here, CC0 makes sense as well.

**Comment by frankhuettner** [comment]
MIT

**Comment by BeastyBlacksmith** [comment]
Ok, thats MIT then. Thanks for getting this done quickly :)
