### ISSUE TITLE
Next workshop

### ISSUE THREAD

**Issue by BeastyBlacksmith** [julia-users-berlin/julia-users-workshop#2]
I would like to target November/December 2019 for the next workshop.
First thing to fix are location and date. I think its the easiest to try to get a spot at opentechschool again and I also liked the saturday.
Looking at their [calendar](https://www.meetup.com/de-DE/opentechschool-berlin/events/calendar/2019-12/) these dates are open:
- 23.11.
- 30.11.
- 07.12.
- 14.12.

Which would be all fine for me. Maybe go for 10am-4pm this time?

CC: @pfitzseb @daveh19 @rschwarz

**Comment by pfitzseb** [comment]
Sounds good. I think I can make time on all of those dates (note that the 22. and 29. are not saturdays though).

**Comment by BeastyBlacksmith** [comment]
all of them should be saturdays

**Comment by rschwarz** [comment]
I already know that 7.12. will not work for me, but otherwise I can only tell on relatively short notice.

**Comment by daveh19** [comment]
I was away last week. Right now, all 4 dates are free for me. I might have something on the 7th - let me find out and get back to you tomorrow if I do. I'm the opposite of Robert, if we book it early I find it easier to commit :)

**Comment by BeastyBlacksmith** [comment]
I finally read Sebastians comment the right way and changed 22.11. -> 23.11. and 29.11. -> 30.11.

**Comment by daveh19** [comment]
The 7th is the one day that I probably have another appointment.

**Comment by BeastyBlacksmith** [comment]
Okay, I will send a request to OpenTechSchool about the other dates than.

**Comment by BeastyBlacksmith** [comment]
I got an answer! So all dates are free and reserved until we decide which one. My favourite day would be 23.11., what is yours?

**Comment by BeastyBlacksmith** [comment]
also have a peek at https://github.com/julia-users-berlin/julia-users-workshop/pull/3 for the outline that gets put onto meet-up for advertisment. I think it would be good to have the julia users berlin logo on there.
Ideas welcome.

**Comment by pfitzseb** [comment]
23.11. sounds good to me.

**Comment by daveh19** [comment]
I'm good with 23.11 also.

**Comment by BeastyBlacksmith** [comment]
That is settled then. Next julia workshop at 23.11.19 at Co.up Berlin.
I am thinking about asking them to reserve a spot for us every half-a-year. That seems doable to me.

**Comment by daveh19** [comment]
Thanks Simon

**Comment by BeastyBlacksmith** [comment]
The stuff that is left to decide is:
 - who is giving a talk? (https://github.com/julia-users-berlin/julia-users-workshop/issues/4)
 -  do we want to have a meeting before the workshop other than the JUB-November meeting?

Not necessary, but a good idea would be good to check if our material is still relevant (https://github.com/julia-users-berlin/julia-users-workshop/issues/5)

**Comment by BeastyBlacksmith** [comment]
The event is live on meet-up now: https://www.meetup.com/de-DE/opentechschool-berlin/events/266022112/
Spread the word!

**Comment by BeastyBlacksmith** [comment]
Would be actually good to have a section for the workshops on the julia-users-berlin homepage

**Comment by rschwarz** [comment]
Yes, we should also post it on the static website.
Do we already have a date & topic for the next usual meetup? It would be best to update that as well, since it will happen before?

**Comment by rschwarz** [comment]
OK, I added the date, location and link to the website. Feel free to add more info there.

**Comment by BeastyBlacksmith** [comment]
The pre-workshop meeting will take place at James-Simon park on 22nd of November, 4pm.

**Comment by BeastyBlacksmith** [comment]
Next workshop will be is planned to be in May 2020.

**Comment by BeastyBlacksmith** [comment]
And then came corona...
