### ISSUE TITLE
Review workshop material

### ISSUE THREAD

**Issue by BeastyBlacksmith** [julia-users-berlin/julia-users-workshop#5]
Especially with respect to 1.x compability

The data in question is [this](https://github.com/julia-users-berlin/julia-users-workshop/blob/master/list_of_resources.md).
Some stuff is pretty old and may not be updated. It would also make sense to spilt it more into what is useful for beginners and what is more of interest for more experienced programmers.

**Comment by daveh19** [comment]
Thanks @BeastyBlacksmith. Will we have time to do this together tomorrow? I'm sick today.

From my point of view, there are three tasks
1. Content for beginners (to programming)
2. Content for experienced programmers
3. Make it all 1.x compatible

**Comment by BeastyBlacksmith** [comment]
Lets but it at the end tomorrow. We should at least mark stuff that is outdated.

**Comment by BeastyBlacksmith** [comment]
done with @pfitzseb
